%version_info

% James Bordner and Faisal Saied
% Department of Computer Science
% University of Illinois at Urbana-Champaign
% 10 April 1995

function version_info
%
%
%

demo_globals

page=[	'               Version Information               ';...
        '                                                 ';...
        '                                                 ';...
        ' June 8, 1995                                    ';...
        '                                                 ';...
        ' This is the first release of MGLab (Version 1.0)';...
        '                                                 ';...
        ' James Bordner   bordner@cs.uiuc.edu             ';...
        ' Faisal Saied    saied@cs.uiuc.edu               ';...
        '                                                 ';...
        ' University of Illinois at Urbana-Champaign      ';...
        ' Department of Computer Science                  ';...
        '                                                 ';...
        ' Please e-mail comments, suggestions, bug reports';...
        ' to James Bordner.                               ';...
        ' We are also interested in hearing about how you ';...
        ' obtained MGLab (ftp to UIUC, MGNET).            ';...
        '                                                 ';...
        ' Please include the string MGLab in the subject  ';...
        ' field.                                          ';...
        '                                                 ';...
        '                                                 ';...
        '                                                 ';...
];

DEMO_INFO_FIG = figure('Position', [30 30 500 600],...
	   'Name', 'Version Info',...
	   'NumberTitle', 'off', ...
	   'Color','blue');


[mm,nn] = size(page);

subplot(1,1,1)
hold off
cla

ht = 0.95;
for j = 1:mm
   text(0.05, ht, page(j,:))
   axis('off')
   ht = ht - 0.04;
end

cb_uic_close = 'close(DEMO_INFO_FIG)';

demo1_uic_close = uicontrol(	'Position', [0.55 0.05 0.20 0.07],...
		'units', 'normalized',...
		'style', 'pushbutton', ...
		'string', 'Close',...
		'backgroundcolor', 'cyan',...
		'foregroundcolor', [0 0 0],...
		'callback', cb_uic_close);


